USE DiscDB
INSERT INTO Cost VALUES ('1', 'DX', '7.99')
INSERT INTO Cost VALUES ('2', 'R-Pro', '12.99')
INSERT INTO Cost VALUES ('3', 'XT', '15.99')
INSERT INTO Cost VALUES ('4', 'Champion', '16.99')
INSERT INTO Cost VALUES ('5', 'Star', '17.99')
INSERT INTO Cost VALUES ('6', 'Fission', '18.99')
INSERT INTO Cost VALUES ('7', 'SoftRubber', '19.99')

INSERT INTO Zip VALUES ('49684', 'Lake Ann', 'Michigan')
INSERT INTO Zip VALUES ('49685', 'Traverse City', 'Michigan')
INSERT INTO Zip VALUES ('49686', 'Cedar', 'Michigan')
INSERT INTO Zip VALUES ('53658', 'Cadilac', 'Michigan')
INSERT INTO Zip VALUES ('59387', 'Detroit', 'Michigan')

INSERT INTO Discs VALUES ('1', 'Berg', 'Kastaplast', 'Putt', 'Stable', '7', '180')
INSERT INTO Discs VALUES ('2', 'Aviar', 'Innova', 'Putt', 'Stable', '4', '175')
INSERT INTO Discs VALUES ('3', 'P1', 'Northwoods', 'Putt', 'Overstable', '5', '180')
INSERT INTO Discs VALUES ('4', 'Buzz', 'Discraft', 'Wedge', 'Strait', '5', '165')
INSERT INTO Discs VALUES ('5', 'Roc', 'Innova', 'Wedge', 'Overstable', '2', '180')
INSERT INTO Discs VALUES ('6', 'Rhino', 'Innova', 'Wedge', 'Overstable', '2', '175')
INSERT INTO Discs VALUES ('7', 'Mako', 'Innova', 'Midrange', 'Strait', '3', '190')
INSERT INTO Discs VALUES ('8', 'Tesla', 'MVP', 'Fairway', 'Overstable', '6', '170')
INSERT INTO Discs VALUES ('9', 'Kaxe', 'Kastaplast', 'Fairway', 'Stable', '7', '180')
INSERT INTO Discs VALUES ('10', 'Valkyrie', 'Innova', 'Distance', 'Stable', '1', '165')
INSERT INTO Discs VALUES ('11', 'FL', 'Innova', 'Fairway', 'Overstable', '5', '175')
INSERT INTO Discs VALUES ('12', 'Condor', 'Innova', 'Distance', 'Stable', '1', '200')
INSERT INTO Discs VALUES ('13', 'Warship', 'Northwoods', 'Distance', 'Overstable', '5', '185')
INSERT INTO Discs VALUES ('14', 'Photon', 'MVP', 'Distance', 'Overstable', '6', '160')
INSERT INTO Discs VALUES ('15', 'Ibex', 'Vibram', 'Midrange', 'Understable', '7', '170')
INSERT INTO Discs VALUES ('16', 'Obex', 'Vibram', 'Midrange', 'Stable', '7', '175')
INSERT INTO Discs VALUES ('17', 'Ridge', 'Vibram', 'Wedge', 'Stable', '7', '180')
INSERT INTO Discs VALUES ('18', 'Summit', 'Vibram', 'Putt', 'Understable', '7', '185')

INSERT INTO Course VALUES ('1', 'Hickory', '1812 Randolph St', '49685')
INSERT INTO Course VALUES ('2', 'Myles Kimmerly', '3333 Maple Dr', '49686')
INSERT INTO Course VALUES ('3', 'Carlys Playground', 'Co rd 221', '49684')
INSERT INTO Course VALUES ('4', 'Blair', '1010 Steve St', '49684')
INSERT INTO Course VALUES ('5', 'Lake Ann', '1133 Ridge Way', '49685')
INSERT INTO Course VALUES ('6', 'Log Lake', '562 Ra-Wa-Si', '49685')
INSERT INTO Course VALUES ('7', 'Garbage Hill', '2108 Spring Dr', '53658')
INSERT INTO Course VALUES ('8', 'Flip City', '5525 Herkner Rd', '59387')

INSERT INTO League VALUES ('1', 'DiskChuckers', '1', '50')
INSERT INTO League VALUES ('2', 'Northwoods', '1', '20')
INSERT INTO League VALUES ('3', 'DiskChuckers', '2', '10')
INSERT INTO League VALUES ('4', 'Northwoods', '2', '30')
INSERT INTO League VALUES ('5', 'DiskChuckers', '3', '10')
INSERT INTO League VALUES ('6', 'Northwoods', '3', '15')
INSERT INTO League VALUES ('7', 'Steves Crew', '4', '30')
INSERT INTO League VALUES ('8', 'Steves Crew', '5', '30')
INSERT INTO League VALUES ('9', 'Steves Crew', '6', '10')
INSERT INTO League VALUES ('10', 'Chuck em', '7', '40')
INSERT INTO League VALUES ('11', 'Chuck em', '8', '50')

INSERT INTO CourseDisc VALUES ('1', '1')
INSERT INTO CourseDisc VALUES ('1', '6')
INSERT INTO CourseDisc VALUES ('1', '7')
INSERT INTO CourseDisc VALUES ('1', '8')
INSERT INTO CourseDisc VALUES ('1', '14')
INSERT INTO CourseDisc VALUES ('2', '1')
INSERT INTO CourseDisc VALUES ('2', '5')
INSERT INTO CourseDisc VALUES ('2', '6')
INSERT INTO CourseDisc VALUES ('2', '7')
INSERT INTO CourseDisc VALUES ('2', '14')
INSERT INTO CourseDisc VALUES ('3', '1')
INSERT INTO CourseDisc VALUES ('3', '6')
INSERT INTO CourseDisc VALUES ('3', '7')
INSERT INTO CourseDisc VALUES ('3', '14')
INSERT INTO CourseDisc VALUES ('3', '15')
INSERT INTO CourseDisc VALUES ('4', '1')
INSERT INTO CourseDisc VALUES ('4', '3')
INSERT INTO CourseDisc VALUES ('4', '4')
INSERT INTO CourseDisc VALUES ('4', '6')
INSERT INTO CourseDisc VALUES ('4', '16')
INSERT INTO CourseDisc VALUES ('5', '1')
INSERT INTO CourseDisc VALUES ('5', '2')
INSERT INTO CourseDisc VALUES ('5', '5')
INSERT INTO CourseDisc VALUES ('5', '6')
INSERT INTO CourseDisc VALUES ('5', '17')
INSERT INTO CourseDisc VALUES ('6', '1')
INSERT INTO CourseDisc VALUES ('6', '2')
INSERT INTO CourseDisc VALUES ('6', '6')
INSERT INTO CourseDisc VALUES ('6', '15')
INSERT INTO CourseDisc VALUES ('6', '18')
